version: "3.8"

services:
  api:
    build:
      context: .
      target: dev
    container_name: expenses_tracker_api
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app # Mount local code into container
      - /usr/src/app/node_modules
    env_file:
      - .env.local
    depends_on:
      - db
    command: ["/usr/src/app/wait-for.sh", "db:3306", "--", "npm", "run", "dev"]

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: expensestracker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
